CREATE DATABASE Prog_Database

USE Prog_Database

CREATE TABLE Venue( 
	VenueID INT NOT NULL PRIMARY KEY,
	VenueName VARCHAR(100) NOT NULL,
	City VARCHAR(100) NOT NULL,
	Province VARCHAR(100) NOT NULL
);

CREATE TABLE Users(
	UserID INT NOT NULL PRIMARY KEY,
	FullName VARCHAR(100) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	Role VARCHAR(100) NOT NULL,
	PhoneNumber VARCHAR(100) NOT NULL
);
